#!/usr/bin/env python -O
# compute per-token tagging accuracy
# Kyle Gorman <gormanky@ohsu.edu>

from __future__ import division

from nltk import str2tuple
from sys import argv, stdout

USAGE = 'USAGE: {} [HYPOTHESES] [GOLD]'.format(__file__)


def get_tags(line):
    return [str2tuple(wt)[1] for wt in line.strip().split()]

if __name__ == '__main__':
    # check arguments
    if len(argv) != 3:
        exit(USAGE)
    # compute and report accuracy
    total = correct = 0
    with open(argv[1], 'r') as hypothesis, open(argv[2], 'r') as gold:
        for (hline, gline) in zip(hypothesis, gold):
            for (htag, gtag) in zip(get_tags(hline), get_tags(gline)):
                total += 1
                correct += (htag == gtag)
    print 'Accuracy: {:.04}'.format(correct / total)
