#!/usr/bin/env python -O
# tokenize: apply the Treebank tokenizer
# Kyle Gorman <gormanky@ohsu.edu>

from __future__ import division

import fileinput

from nltk import word_tokenize


if __name__ == '__main__':
    for line in fileinput.input():
        print ' '.join(word_tokenize(line.strip()))
