#!/usr/bin/env python -O
# convert PTB-style trees to token/tag strings, assuming one tree per line
# Kyle Gorman <gormanky@ohsu.edu>

import fileinput

from nltk import tuple2str, Tree 


if __name__ == '__main__':
    for line in fileinput.input():
        print ' '.join(tuple2str(wt) for wt in Tree.parse(line))
