#!/usr/bin/env python -O
# untag: remove tags from tagged data files
# Kyle Gorman <gormanky@ohsu.edu>

from __future__ import division

import fileinput

from nltk import str2tuple, untag


if __name__ == '__main__':
    for line in fileinput.input():
        print ' '.join(untag(str2tuple(wt) for wt in line.strip().split()))
